#cloud-config
packages:
  - htop
  - docker

timezone: ${timezone}

device_aliases: { 'minecraft_data': '${device_name}' }
disk_setup:
  minecraft_data:
    table_type: gpt
    layout: true

fs_setup:
  - device: minecraft_data
    label: Minecraft
    filesystem: xfs
    partition: any

mounts:
  - [
      'minecraft_data',
      '${minecraft_data_path}',
      'xfs',
      'defaults,nofail',
      '0',
      '2',
    ]

runcmd:
  - systemctl daemon-reload
  # Finish Duck DNS setup
  - systemctl enable duck.service
  - systemctl start duck.service
  # Initialize Minecraft server
  - chown ec2-user:ec2-user -R ${minecraft_data_path} # Fix permissions
  # - systemctl enable minecraft.timer
  # - systemctl start minecraft.timer
  - docker-compose -f ${minecraft_data_path}/docker-compose.yml up -d

write_files:
  # Duck DNS files
  - path: /home/ec2-user/duck.sh
    permissions: '0744'
    owner: ec2-user
    defer: true
    encoding: base64
    content: ${duckdns_script_file_content_b64}
  - path: /etc/systemd/system/duck.service
    defer: true
    encoding: base64
    content: ${duckdns_service_file_content_b64}

  # Minecraft files
  - path: /etc/systemd/system/minecraft.service
    defer: true
    encoding: base64
    content: ${minecraft_service_file_content_b64}
  - path: ${minecraft_data_path}/docker-compose.yml
    permissions: '0744'
    owner: ec2-user
    defer: true
    encoding: base64
    content: ${minecraft_compose_file_content_b64}

  - path: /home/ec2-user/minecraft_shutdown.sh
    defer: true
    encoding: base64
    content: ${minecraft_shutdown_script_file_content_b64}
  - path: /etc/systemd/system/minecraft_shutdown.service
    defer: true
    encoding: base64
    content: ${minecraft_shutdown_service_file_content_b64}
  - path: /etc/systemd/system/minecraft_shutdown.timer
    defer: true
    encoding: base64
    content: ${minecraft_shutdown_timer_file_content_b64}
