#cloud-config
packages:
  - htop
  - docker

bootcmd:
  # cloud-init runs before EBS volume mount (sometimes?), so we have to wait. See https://stackoverflow.com/a/77868589/11138267
  - echo "$(date --rfc-3339=ns) | Waiting for EBS volume device to be available"
  - echo "$(lsblk)"
  - timeout 30s sh -c 'while [ ! -e ${device_name} ]; do sleep 1; done'
  - echo "$(date --rfc-3339=ns) | Device found"
  - echo "$(lsblk)"

timezone: ${timezone}

device_aliases: { "data": "${device_name}" }
disk_setup:
  data:
    table_type: gpt
    layout: true
    overwrite: true

fs_setup:
  - device: data
    label: Server_Data
    filesystem: xfs
    partition: any
    overwrite: true

mounts:
  - ["data", "${data_path}", "xfs", "defaults,nofail", "0", "2"]

write_files:
  # Duck DNS files
  - path: /home/ec2-user/duck.sh
    permissions: "0744"
    owner: ec2-user
    defer: true
    encoding: base64
    content: ${duckdns_script_file_content_b64}
  - path: /etc/systemd/system/duck.service
    defer: true
    encoding: base64
    content: ${duckdns_service_file_content_b64}

  # Minecraft files
  - path: /etc/systemd/system/minecraft.service
    defer: true
    encoding: base64
    content: ${minecraft_service_file_content_b64}
  - path: ${minecraft_data_path}/docker-compose.yml
    owner: ec2-user
    defer: true
    encoding: base64
    content: ${minecraft_compose_file_content_b64}

  # Minecraft shutdown files
  - path: /home/ec2-user/minecraft_shutdown.sh
    defer: true
    owner: ec2-user
    permissions: "0744"
    encoding: base64
    content: ${minecraft_shutdown_script_file_content_b64}
  - path: /etc/systemd/system/minecraft_shutdown.service
    defer: true
    encoding: base64
    content: ${minecraft_shutdown_service_file_content_b64}
  - path: /etc/systemd/system/minecraft_shutdown.timer
    defer: true
    encoding: base64
    content: ${minecraft_shutdown_timer_file_content_b64}

runcmd:
  - lsblk
  - cat /etc/fstab
  - systemctl daemon-reload
  # Finish Duck DNS setup
  - systemctl enable duck.service
  - systemctl start duck.service
  # Manually install Docker Compose plugin
  - mkdir -p /usr/local/lib/docker/cli-plugins
  - [
      curl,
      -SL,
      "https://github.com/docker/compose/releases/download/v2.27.1/docker-compose-linux-aarch64",
      -o,
      /usr/local/lib/docker/cli-plugins/docker-compose,
    ]
  - chmod +x /usr/local/lib/docker/cli-plugins/docker-compose
  # Finish Docker setup
  - usermod -a -G docker ec2-user # Allow docker commands without sudo
  - systemctl enable docker
  - systemctl start docker
  # Initialize Minecraft server
  - chown ec2-user:ec2-user -R ${minecraft_data_path} # Fix permissions
  - systemctl enable minecraft
  - systemctl start minecraft
  - systemctl enable minecraft_shutdown.timer
  - systemctl start minecraft_shutdown.timer
